apiVersion: v1
kind: Service
metadata:
  name: dev-order-service
  labels:
    app: dev-order-service
spec:
  type: NodePort
  ports:
    - port: 50004
      protocol: TCP
      targetPort: 50004
  selector:
    app: dev-order-service