apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-order-service-db-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /order-data
    type: ''
  storageClassName: "manual"
  accessModes: ["ReadWriteOnce"]
  claimRef:
    name: dev-order-service-pvc
    namespace: default
